# Generated by Django 6.0.6 on 2026-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0002_alter_membershipcard_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcard',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
