# Generated by Django 6.0.6 on 2026-06-17 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0003_alter_membershipcard_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='login_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_types',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused'), ('S', 'Sick Leave')], default='A', max_length=1, verbose_name='Attendance Type'),
        ),
    ]
