# Generated by Django 6.0.6 on 2026-08-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_resources/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='other', max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, default='Team Member', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='teamcc.project')),
            ],
        ),
    ]
