# Generated by Django 6.0.6 on 2026-08-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0008_projectresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesheet',
            name='category',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Event', 'Event'), ('Rules & Regulations', 'Rules & Regulations'), ('Mentioned Member only', 'Mentioned Member only')], default='Announcement', max_length=50),
        ),
    ]
