# Generated by Django 6.0.6 on 2026-08-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0009_noticesheet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesheet',
            name='mentioned_members',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noticesheet',
            name='target_audience',
            field=models.TextField(blank=True, default='All Members'),
        ),
    ]
