# Generated by Django 6.0.6 on 2026-08-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0011_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesheet',
            name='author',
            field=models.CharField(blank=True, default='Lead Administrator', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticesheet',
            name='priority',
            field=models.CharField(choices=[('General', 'General'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent'), ('Critical', 'Critical'), ('Low', 'Low')], default='General', max_length=20),
        ),
    ]
