# Generated by Django 6.0.6 on 2026-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamcc', '0013_project_assignment_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_resources/%Y/%m/'),
        ),
    ]
